"""The Gateway Router leg: ``GR_REQUEST``/``GR_RESPONSE``, and the TLS wrapper
Phase 4 put around it.

There was no unit test for this listener before this file: ``nsesupport``'s
default config disables the router (``"gateway_router": {"enabled": False}``),
because every other NSE test drives a box straight through
:class:`exchangesim.nnf.session.BoxConnection` rather than through a real
socket. Here the router is enabled and driven for real, on the venue's own
reactor, since ``GatewayRouter`` -- unlike a box connection -- is a genuine
:class:`exchangesim.core.reactor.Listener` with no fake-transport seam.

Two client shapes are used, matching how each policy needs to be driven:

* At policy ``"none"`` a blocking client socket plus :func:`tests.support.pump`
  is enough -- the same pattern :mod:`tests.test_fix_acceptor` uses for the
  FIX acceptor, and just as free of threads and sleeps.
* At policy ``"1.2"`` the conversation must ride a real TLS handshake, which
  needs a *non-blocking* client so the reactor can service both ends of the
  loopback connection itself: :meth:`exchangesim.core.reactor.Reactor.connect`
  with a :class:`exchangesim.tls.transport.TlsTransport`, pumped with
  :func:`tests.support.pump_until` exactly as the task describes.

Certificates are generated **once**, at module scope, into a ``tempfile``
directory rather than the repository's own ``var/`` -- RSA-2048 keygen is the
slow part of any TLS test here (see ``tests/test_tls_transport.py``'s module
docstring), and every ``"1.2"`` test in this file points its venue at the same
pre-populated ``tls_dir`` so ``CertificateStore.ensure()`` finds a matching,
unexpired certificate already on disk and never regenerates one.
"""

import atexit
import datetime
import shutil
import socket
import ssl
import tempfile
import unittest

from exchangesim.core.config import ConfigError
from exchangesim.fix.message import Message
from exchangesim.fix.render import REDACTED
from exchangesim.nnf import crypto
from exchangesim.nnf.codec import NnfCodec
from exchangesim.tls import certs, context, rsa, x509
from exchangesim.tls.transport import TlsTransport
from exchangesim.venues.nse import dictionary as D
from exchangesim.venues.nse import gateway_router
from exchangesim.venues.nse import transactions as X

from tests.nsesupport import (BOX_ONE, BROKER_ONE, BROKER_TWO, BoxClient,
                             VenueHarness, venue_config)
from tests.support import connect, pump, pump_until

UNKNOWN_BOX = 999

USER_IP_REC_NOT_FOUND = "16588"
INVALID_BROKER_OR_BRANCH = "16041"


# ---------------------------------------------------------------------------
# Certificate fixture: built once, on import, never regenerated by a test.
# ---------------------------------------------------------------------------

def _build_fixture():
    tls_dir = tempfile.mkdtemp(prefix="exsim-nse-gr-")
    # Matches exactly what NseVenue._build_tls asks for when
    # gateway_router.host is "127.0.0.1" and no tls_names override is given:
    # common_name=host, names=(host, "localhost") after de-duplication. Same
    # parameters here means the venue's own CertificateStore.ensure() call
    # finds this fixture's files already good and never re-generates them.
    store = certs.CertificateStore(tls_dir, common_name="127.0.0.1",
                                   names=("127.0.0.1", "localhost"))
    issued = store.ensure()

    wrong_dir = tempfile.mkdtemp(prefix="exsim-nse-gr-wrong-")
    wrong_key = rsa.generate(2048)
    wrong_ca_der = x509.self_signed_ca(
        wrong_key, "A Different CA", "ExchangeSim", days=3650, serial=1,
        now=datetime.datetime(2026, 1, 1))
    wrong_ca_pem = wrong_dir + "/wrong-ca.pem"
    with open(wrong_ca_pem, "wb") as handle:
        handle.write(rsa.to_pem(wrong_ca_der, "CERTIFICATE").encode("ascii"))

    return tls_dir, wrong_dir, issued, wrong_ca_pem


_TLS_DIR, _WRONG_DIR, _ISSUED, _WRONG_CA_PEM = _build_fixture()
_CA_PEM = _ISSUED.ca_certificate

atexit.register(shutil.rmtree, _TLS_DIR, True)
atexit.register(shutil.rmtree, _WRONG_DIR, True)


def _strings_in(value):
    """Every string reachable inside a nested dict/list/tuple structure."""
    if isinstance(value, dict):
        for item in value.values():
            for found in _strings_in(item):
                yield found
    elif isinstance(value, (list, tuple)):
        for item in value:
            for found in _strings_in(item):
                yield found
    elif isinstance(value, str):
        yield value


def gr_config(**router):
    """A venue config with the Gateway Router enabled on an OS-chosen port."""
    settings = {"enabled": True, "host": "127.0.0.1", "port": 0,
                "encryption": "new"}
    settings.update(router)
    return venue_config(gateway_router=settings)


# ---------------------------------------------------------------------------
# A blocking client, for the un-encrypted conversation
# ---------------------------------------------------------------------------

class GrBlockingClient(object):
    """A blocking client socket that speaks just enough NNF for the router."""

    def __init__(self, address, layouts):
        self.sock = connect(address)
        self.codec = NnfCodec(layouts, client=True)
        self._framer = self.codec.framer()

    def request(self, box_id, broker_id):
        message = Message.create(str(X.GR_REQUEST))
        message.set(D.ERROR_CODE, "0")
        message.set(D.BOX_ID, str(box_id))
        message.set(D.BROKER_ID, broker_id)
        self.sock.sendall(self.codec.encode(message))
        return message

    def send_other(self, code, fields):
        message = Message.create(str(code))
        message.set(D.ERROR_CODE, "0")
        for tag, value in sorted((fields or {}).items()):
            message.set(tag, str(value))
        self.sock.sendall(self.codec.encode(message))
        return message

    def receive(self, timeout=0.5):
        self.sock.settimeout(timeout)
        try:
            chunk = self.sock.recv(65536)
        except socket.timeout:
            return []
        if not chunk:
            return []
        return [self.codec.decode(raw) for raw in self._framer.feed(chunk)]

    def eof(self, timeout=0.5):
        """Whether the peer has closed the connection."""
        self.sock.settimeout(timeout)
        try:
            chunk = self.sock.recv(65536)
        except socket.timeout:
            return False
        return chunk == b""

    def close(self):
        try:
            self.sock.close()
        except OSError:
            pass


# ---------------------------------------------------------------------------
# A non-blocking, reactor-driven client, for the TLS conversation
# ---------------------------------------------------------------------------

class GrReactorClient(object):
    """One Gateway Router conversation driven on the venue's own reactor."""

    def __init__(self, reactor, address, layouts, transport=None):
        self.codec = NnfCodec(layouts, client=True)
        self._framer = self.codec.framer()
        self.received = []
        self.closed = False
        self.conn = reactor.connect(address[0], address[1],
                                    self._on_connect, self._on_error,
                                    transport=transport)
        self.conn.on_data = self._on_data
        self.conn.on_close = self._on_close

    def _on_connect(self, conn):
        pass

    def _on_error(self, conn, exc):
        pass

    def _on_data(self, conn, chunk):
        for raw in self._framer.feed(chunk):
            self.received.append(self.codec.decode(raw))

    def _on_close(self, conn):
        self.closed = True

    def request(self, box_id, broker_id):
        message = Message.create(str(X.GR_REQUEST))
        message.set(D.ERROR_CODE, "0")
        message.set(D.BOX_ID, str(box_id))
        message.set(D.BROKER_ID, broker_id)
        self.conn.send(self.codec.encode(message))
        return message


# ---------------------------------------------------------------------------
# Policy "none": fast, no keygen at all
# ---------------------------------------------------------------------------

class PlainRouterTest(unittest.TestCase):

    def setUp(self):
        self.harness = VenueHarness(gr_config(tls="none"))
        self.addCleanup(self.harness.close)
        self.address = self.harness.venue.router.address

    def _client(self):
        client = GrBlockingClient(self.address, self.harness.venue.layouts)
        self.addCleanup(client.close)
        return client

    def test_a_configured_box_is_granted_secrets(self):
        client = self._client()
        client.request(BOX_ONE, BROKER_ONE)
        pump(self.harness.reactor)

        received = client.receive()

        self.assertEqual(1, len(received))
        response = received[0]
        self.assertEqual(str(X.GR_RESPONSE), response.msg_type)
        self.assertEqual(str(X.NO_ERROR), response.get(D.ERROR_CODE))
        self.assertEqual(
            list(self.harness.venue.acceptor.address[:2]),
            [response.get(D.IP_ADDRESS), int(response.get(D.PORT))])

        secrets = self.harness.venue.issued(BOX_ONE)
        self.assertIsNotNone(secrets)
        self.assertEqual(secrets.session_key, response.get(D.SESSION_KEY))

    def test_a_box_disconnecting_discards_what_it_was_issued(self):
        """The document resets the IVs at the exchange on a box disconnection
        and expects a fresh GR query for the next connection. Holding them
        would hand a cipher to a box that reconnected without dialling the
        router, garbling the connection rather than refusing it -- and, with
        require_encryption off, making a plain reconnect impossible on any box
        that had ever collected a key."""
        client = self._client()
        client.request(BOX_ONE, BROKER_ONE)
        pump(self.harness.reactor)
        self.assertIsNotNone(self.harness.venue.issued(BOX_ONE))

        member = BoxClient(self.harness.venue, BOX_ONE, BROKER_ONE)
        member.box.detach("test")

        self.assertIsNone(self.harness.venue.issued(BOX_ONE))

    def test_an_unconfigured_box_is_refused(self):
        client = self._client()
        client.request(UNKNOWN_BOX, BROKER_ONE)
        pump(self.harness.reactor)

        response = client.receive()[0]
        self.assertEqual(USER_IP_REC_NOT_FOUND, response.get(D.ERROR_CODE))
        self.assertIsNone(self.harness.venue.issued(UNKNOWN_BOX))

    def test_a_box_dialling_with_the_wrong_broker_is_refused(self):
        client = self._client()
        client.request(BOX_ONE, BROKER_TWO)
        pump(self.harness.reactor)

        response = client.receive()[0]
        self.assertEqual(INVALID_BROKER_OR_BRANCH, response.get(D.ERROR_CODE))

    def test_anything_but_a_gr_request_closes_the_connection(self):
        client = self._client()
        client.send_other(X.BOX_SIGN_ON_REQUEST_IN,
                          {D.BOX_ID: BOX_ONE, D.BROKER_ID: BROKER_ONE})
        pump(self.harness.reactor)

        self.assertEqual([], client.receive())
        self.assertTrue(client.eof())

    def test_the_conversation_is_audited_with_credentials_redacted(self):
        client = self._client()
        client.request(BOX_ONE, BROKER_ONE)
        pump(self.harness.reactor)
        client.receive()

        entries = self.harness.venue.audit.entries(limit=50).entries
        request_entry = [e for e in entries if e.type == str(X.GR_REQUEST)][0]
        response_entry = [e for e in entries if e.type == str(X.GR_RESPONSE)][0]
        self.assertEqual("nnf", request_entry.protocol)
        self.assertEqual("nnf", response_entry.protocol)
        self.assertEqual("in", request_entry.direction)
        self.assertEqual("out", response_entry.direction)

        opened = self.harness.command("audit.entry", seq=response_entry.seq)
        redacted = dict((row["name"], row["redacted"])
                       for row in opened["fields"])
        for name in ("SessionKey", "CryptographicKey",
                     "StaticCryptographicIV", "DynamicCryptographicIV",
                     "CryptographicAdditionalKey"):
            self.assertTrue(redacted[name], name)
        values = dict((row["name"], row["value"]) for row in opened["fields"])
        for name in redacted:
            if redacted[name]:
                self.assertEqual(REDACTED, values[name])


# ---------------------------------------------------------------------------
# What the router issues, and where it points a member
# ---------------------------------------------------------------------------

class _FakeSocket(object):
    """Just enough of a socket for :meth:`GatewayRouter._gateway_address`."""

    def __init__(self, local):
        self._local = local

    def getsockname(self):
        return self._local


class _FakeConnection(object):

    def __init__(self, local):
        self.sock = _FakeSocket(local)


class IssuedSecretsTest(unittest.TestCase):
    """The cryptographic material, and the two readings of its dynamic IV.

    A real client failed to decrypt the very first message the exchange sent
    after box sign-on, and the cause was here rather than in GCM: the IV a
    member hands OpenSSL is the memory of a C struct holding a ``long long``
    (CM 6.6 p.256, F&O 9.50 p.315), so its dynamic half is laid out the host's
    way and not the wire's. Both ends of a simulator get that wrong together
    and round-trip perfectly, which is why nothing here caught it -- so these
    tests build the two halves *separately*, the way the wire does.
    """

    def setUp(self):
        self.harness = VenueHarness(gr_config(tls="none"))
        self.addCleanup(self.harness.close)
        self.router = self.harness.venue.router

    def _client(self):
        client = GrBlockingClient(self.router.address,
                                  self.harness.venue.layouts)
        self.addCleanup(client.close)
        return client

    def _secrets(self, **router):
        return gateway_router.issue(BOX_ONE, "new", **router)

    def test_the_dynamic_half_of_the_iv_is_issued_as_zero(self):
        # Not laziness: at zero, a member that byte-swaps the Gateway Router's
        # LONG LONG out of the response and a member that copies it straight
        # into the IV struct hold the same number, so one whole reading of the
        # document stops being able to disagree. The static half is still
        # random, and the key is fresh per connection, which is what GCM
        # actually requires.
        secrets = self._secrets()
        self.assertEqual(b"\x00" * 8, secrets.iv[8:])
        self.assertNotEqual(b"\x00" * 8, secrets.iv[:8])

        client = self._client()
        client.request(BOX_ONE, BROKER_ONE)
        pump(self.harness.reactor)
        self.assertEqual("0", client.receive()[0].get(D.DYNAMIC_IV))

    def test_the_exchange_finds_the_layout_a_member_actually_uses(self):
        for endian in ("little", "big"):
            secrets = self._secrets(dynamic_endian="auto")
            member = crypto.NewCipher(secrets.key, secrets.iv,
                                      secrets.additional_key, client=True,
                                      dynamic_endian=endian)
            exchange = secrets.exchange_cipher()

            sealed, tag = member.seal(b"BOX_SIGN_ON_REQUEST_IN")
            self.assertEqual(b"BOX_SIGN_ON_REQUEST_IN",
                             exchange.open(sealed, tag))
            self.assertEqual(endian, exchange.dynamic_endian)

            # The direction that actually failed against the real client: the
            # answer the exchange sends back must decrypt at the member.
            sealed, tag = exchange.seal(b"BOX_SIGN_ON_REQUEST_OUT")
            self.assertEqual(b"BOX_SIGN_ON_REQUEST_OUT",
                             member.open(sealed, tag))

    def test_a_pinned_layout_refuses_the_other_reading(self):
        # What "auto" is protecting against, and what a member sees without it.
        secrets = self._secrets(dynamic_endian="little")
        member = crypto.NewCipher(secrets.key, secrets.iv,
                                  secrets.additional_key, client=True,
                                  dynamic_endian="big")
        sealed, tag = member.seal(b"BOX_SIGN_ON_REQUEST_IN")
        self.assertRaises(crypto.CryptoError,
                          secrets.exchange_cipher().open, sealed, tag)

    def test_the_member_half_cannot_probe_and_takes_the_default(self):
        secrets = self._secrets(dynamic_endian="auto")
        self.assertEqual("little", secrets.member_endian)
        self.assertEqual("little", secrets.member_cipher().dynamic_endian)

    def test_the_layout_in_force_is_reported_without_the_secrets(self):
        described = self._secrets(dynamic_endian="big").describe()
        self.assertEqual("big", described["dynamic_iv"])
        self.assertEqual([], [text for text in _strings_in(described)
                              if text in (str(self._secrets().key),)])

    def test_an_unknown_dynamic_iv_setting_is_refused_at_startup(self):
        self.assertRaises(ConfigError, VenueHarness,
                          gr_config(tls="none", dynamic_iv="middle"))

    def test_an_advertise_host_too_long_for_the_field_is_refused(self):
        self.assertRaises(ConfigError, VenueHarness,
                          gr_config(tls="none",
                                    advertise_host="192.168.100.1000"))


class GatewayAddressTest(unittest.TestCase):
    """Which address a member is told to bring its encryption to.

    ``IPAddress`` in the GR response is the member's *only* statement of where
    the trading gateway is. A simulator bound to one interface and reached on
    another answered with the bound address, which is the same
    connection-refused the member had already hit on the router itself, one
    step further in.
    """

    def _router(self, bound, **router):
        harness = VenueHarness(gr_config(tls="none", **router))
        self.addCleanup(harness.close)
        router_ = harness.venue.router
        router_._gateway = bound
        return router_

    def test_a_gateway_bound_to_one_interface_names_it(self):
        router = self._router(("10.0.0.7", 9021))
        self.assertEqual(("10.0.0.7", 9021),
                         router._gateway_address(_FakeConnection(("10.0.0.9",
                                                                  40001))))

    def test_a_gateway_bound_to_every_interface_names_the_one_used(self):
        router = self._router(("0.0.0.0", 9021))
        self.assertEqual(("192.168.73.36", 9021),
                         router._gateway_address(
                             _FakeConnection(("192.168.73.36", 40001))))

    def test_advertise_host_overrides_both(self):
        router = self._router(("0.0.0.0", 9021), advertise_host="203.0.113.9")
        self.assertEqual(("203.0.113.9", 9021),
                         router._gateway_address(
                             _FakeConnection(("192.168.73.36", 40001))))

    def test_a_socket_that_cannot_answer_leaves_the_bound_address(self):
        router = self._router(("0.0.0.0", 9021))

        class _Broken(object):
            sock = None

        self.assertEqual(("0.0.0.0", 9021), router._gateway_address(_Broken()))


# ---------------------------------------------------------------------------
# Policy "1.2": a real TLS handshake, on both interpreters
# ---------------------------------------------------------------------------

class Tls12RouterTest(unittest.TestCase):

    def setUp(self):
        self.harness = VenueHarness(
            gr_config(tls="1.2", tls_dir=_TLS_DIR))
        self.addCleanup(self.harness.close)
        self.address = self.harness.venue.router.address
        self.reactor = self.harness.reactor

    def _client_context(self, cafile=_CA_PEM):
        return context.client_context("1.2", cafile)

    def test_the_conversation_completes_over_a_real_handshake(self):
        transport = TlsTransport(self._client_context(), server_side=False,
                                 server_hostname="127.0.0.1")
        client = GrReactorClient(self.reactor, self.address,
                                 self.harness.venue.layouts,
                                 transport=transport)
        client.request(BOX_ONE, BROKER_ONE)

        completed = pump_until(self.reactor, lambda: len(client.received) >= 1)
        self.assertTrue(completed, "no GR_RESPONSE arrived over TLS")

        response = client.received[0]
        self.assertEqual(str(X.GR_RESPONSE), response.msg_type)
        self.assertEqual(str(X.NO_ERROR), response.get(D.ERROR_CODE))
        secrets = self.harness.venue.issued(BOX_ONE)
        self.assertEqual(secrets.session_key, response.get(D.SESSION_KEY))

    def test_a_client_trusting_the_wrong_ca_is_dropped(self):
        transport = TlsTransport(self._client_context(cafile=_WRONG_CA_PEM),
                                 server_side=False,
                                 server_hostname="127.0.0.1")
        client = GrReactorClient(self.reactor, self.address,
                                 self.harness.venue.layouts,
                                 transport=transport)
        client.request(BOX_ONE, BROKER_ONE)

        pump_until(self.reactor,
                  lambda: client.closed or len(client.received) >= 1)

        self.assertTrue(client.closed)
        self.assertEqual([], client.received)

    def test_gateway_router_command_reports_ca_and_fingerprint_but_no_key(self):
        result = self.harness.command("gateway_router")

        self.assertEqual("1.2", result["tls"])
        self.assertEqual(_CA_PEM, result["ca_certificate"])
        self.assertIsNotNone(result["fingerprint"])
        self.assertIsNotNone(result["certificate_expires"])

        for text in _strings_in(result):
            self.assertNotIn("BEGIN", text)
            for component in text.replace("\\", "/").split("/"):
                self.assertNotIn("key", component.lower())


# ---------------------------------------------------------------------------
# Start-up refusal when TLS 1.3 is not available at all
# ---------------------------------------------------------------------------

class Tls13UnavailableTest(unittest.TestCase):

    def test_tls13_is_refused_at_startup_on_an_old_openssl(self):
        if ssl.HAS_TLSv1_3:
            self.skipTest(
                "this interpreter's OpenSSL (%s) supports TLS 1.3, so '1.3' "
                "cannot be shown unavailable here" % ssl.OPENSSL_VERSION)

        # Bogus, non-existent paths: _pin_version raises TlsUnavailable before
        # context.server_context ever tries to open a certificate file, so
        # this never touches disk and pays no keygen cost.
        config = gr_config(tls="1.3", tls_cert="/no/such/cert.pem",
                          tls_key="/no/such/key.pem")

        with self.assertRaises(ConfigError) as caught:
            VenueHarness(config)

        message = str(caught.exception)
        self.assertEqual(
            context.describe_unavailable("1.3", setting_name="gateway_router.tls"),
            message)
        self.assertIn("gateway_router.tls", message)
        self.assertIn("1.2", message)
        self.assertIn("none", message)


if __name__ == "__main__":
    unittest.main()
